export const ErrorCode = {
  User: {
    USER_NOT_FOUND: 'USER_001',
    NO_PERMISSION: 'USER_002',
  },

  Post: {
    POST_NOT_FOUND: 'POST_001',
    NO_PERMISSION: 'POST_002',
    ALREADY_LIKED: 'POST_003',
    LIKE_NOT_FOUND: 'POST_004',
  },

  Comment: {
    COMMENT_NOT_FOUND: 'COMMENT_001',
    NO_PERMISSION: 'COMMENT_002',
    ALREADY_LIKED: 'COMMENT_003',
    LIKE_NOT_FOUND: 'COMMENT_004',
  },
};
