export const ErrorCode = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',

  User: {
    USER_NOT_FOUND: 'USER_001',
    INVALID_PASSWORD: 'USER_002',
    EMAIL_ALREADY_EXISTS: 'USER_003',
  },

  Post: {
    POST_NOT_FOUND: 'POST_001',
    NO_PERMISSION: 'POST_002',
    POST_ALREADY_LIKED: 'POST_003',
    POST_LIKE_NOT_FOUND: 'POST_004',
  },

  Comment: {
    COMMENT_NOT_FOUND: 'COMMENT_001',
    NO_PERMISSION: 'COMMENT_002',
    COMMENT_ALREADY_LIKED: 'COMMENT_003',
    COMMENT_LIKE_NOT_FOUND: 'COMMENT_004',
  },
};
